#!/usr/bin/env bash
# Task Panel claim trigger (Codex) — generated by `install.sh --target codex`.
#
# Polls `issue candidates` and claims the first card that is mine, unless I already
# hold an in_progress card (one card at a time). Safe to run often: it exits 0 when
# there is nothing to claim and never steals a card that is not assigned to me.
#
# Codex has no hooks, so this script is the trigger. Schedule it, e.g. with cron:
#   */5 * * * * {{TRIGGER}}
# `install.sh --target codex --no-automation` skips writing this script.
set -u

name="${TASKCTL_AGENT:-{{AGENT}}}"
shim="{{SHIM}}"

if [ ! -x "$shim" ]; then
  echo "task-panel-claim: taskctl shim not found: $shim" >&2
  exit 1
fi

# One card at a time: skip when I already hold an in_progress card.
held="$("$shim" --json issue list --status in_progress 2>/dev/null || true)"
held_ref="$(printf '%s' "$held" | TP_NAME="$name" node -e '
  let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{let ref="";try{const t=JSON.parse(s).data.tasks||[];const mine=t.find(x=>x.assignee&&x.assignee.display_name===process.env.TP_NAME);ref=mine?mine.identifier:"";}catch{}process.stdout.write(ref);});
')"
if [ -n "$held_ref" ]; then
  echo "task-panel-claim: already holding $held_ref — nothing to claim"
  exit 0
fi

# Claim the first candidate.
cand="$("$shim" --json issue candidates --assignee "$name" 2>/dev/null || true)"
ref="$(printf '%s' "$cand" | node -e '
  let s="";process.stdin.on("data",d=>s+=d).on("end",()=>{let ref="";try{const c=JSON.parse(s).data.candidates||[];ref=c[0]?c[0].identifier:"";}catch{}process.stdout.write(ref);});
')"
if [ -z "$ref" ]; then
  echo "task-panel-claim: no claimable cards for $name"
  exit 0
fi

echo "task-panel-claim: claiming $ref"
"$shim" issue move "$ref" in_progress
