#!/usr/bin/env bash
# wake-codex.sh — hand a fresh handoff to a headless Codex run.
# Generated by `install.sh --target codex`.
#
# Codex has no timer either, so the supervisor (outside the host) starts this.
# `codex exec` runs one non-interactive turn with the given prompt. The Codex
# desktop app's own automation (intervalMinutes / quotaAware / model /
# reasoningEffort) is an alternative wake path — see docs/scheduling.md.
#
#   wake-codex.sh "<handoff>"
set -eu

prompt="${1:-}"

if [ -z "$prompt" ]; then
  echo "wake-codex: a handoff prompt is required" >&2
  exit 2
fi

exec codex exec "$prompt"
