#!/usr/bin/env bash
# wake-pi.sh — hand a fresh handoff to pi.
# Generated by `install.sh --target pi`.
#
# Pi is driven from the agent-skill side and its headless story varies by
# install, so this is the *external scheduler* path: the supervisor starts pi
# with the handoff as its prompt. If your pi has no headless entry point, wire
# the supervisor's `--wake-command` to your own glue, or use the in-session
# trigger described in docs/scheduling.md (the supervisor still does the scan,
# the atomic claim, and the patrol; only the wake is manual).
#
#   wake-pi.sh "<handoff>"
set -eu

prompt="${1:-}"

if [ -z "$prompt" ]; then
  echo "wake-pi: a handoff prompt is required" >&2
  exit 2
fi

exec pi run "$prompt"
