#!/usr/bin/env bash
# taskctl shim — generated by `install.sh --target <host>`.
#
# Injects the installed agent name into every CLI call so each write is attributed
# to this agent even when TASKCTL_AGENT is not present in the environment. The name
# is fixed at install time (--agent-name, default $USER); TASKCTL_AGENT still wins
# when it is set, so a session can override it deliberately.
set -u

agent="${TASKCTL_AGENT:-{{AGENT}}}"
export TASKCTL_AGENT="$agent"
exec node "{{REPO}}/src/cli/index.mjs" --agent "$agent" "$@"
