#!/usr/bin/env bash
# Task Panel SessionStart hook — generated by `install.sh --target claude`.
#
# Runs at the start of every Claude Code session: it starts the board (taskd
# autostarts on first use), lists this agent's claimable cards, and restates the
# eight shared rules. Non-fatal on purpose — a cold board or a missing CLI must
# never block the session.
set -u

name="${TASKCTL_AGENT:-{{AGENT}}}"
shim="{{SHIM}}"

echo
echo "== Task Panel =="

if [ -x "$shim" ] && command -v node >/dev/null 2>&1; then
  echo "-- 分给我的待领卡 (claimable for $name) --"
  "$shim" issue candidates --assignee "$name" 2>&1 || true
else
  echo "-- 分给我的待领卡 --"
  # PATH-independent fallback: the shim lives under the host home and is *not* on
  # PATH, so a bare `taskctl` here would be a command the user cannot run. Name
  # the shim by absolute path, and offer the repo CLI for the case where the shim
  # is missing but node is present.
  echo "(taskctl shim or node not found — try: $shim issue candidates --assignee $name)"
  echo "  or: node {{REPO}}/src/cli/index.mjs --agent $name issue candidates --assignee $name"
fi

echo
echo "-- 八条规矩 --"
cat <<'RULES'
1. claim-first  — 先读 issue candidates --assignee <me>，再 issue move <ref> in_progress
2. 只领该领的    — 别人的卡 / backlog / epic / 有未完成依赖的卡，都不碰
3. 一次一张卡    — 同一时刻只 hold 一张
4. 心跳保鲜      — 每 ≤10 分钟续心跳，别把卡挂 in_progress 闲置
5. 交卡带报告    — 交付必须带报告（delivery gate），否则进不了 in_review
6. 自审≠验收     — 最多到 in_review，done 由人验收
7. 冲突不硬抢    — VERSION_CONFLICT / 过期先重读一次，别盲重试
8. 可追溯        — 每次写都带会话 id
RULES
