#!/usr/bin/env bash
# wake-claude.sh — hand a fresh handoff to a headless Claude Code session.
# Generated by `install.sh --target claude`.
#
# Claude Code has no timer, so the supervisor (outside the host) is what starts
# this. `claude -p` runs Claude Code headless with one prompt and exits; pass a
# session id as the second argument to resume that conversation instead of
# starting fresh.
#
#   wake-claude.sh "<handoff>"            # a fresh headless turn
#   wake-claude.sh "<handoff>" <sid>      # resume session <sid>
#
# The supervisor builds the handoff (bounded: card id, attribution flags, the
# claim-first rules); it invokes this shape directly, and this script is the
# reference you can edit if your Claude Code needs different flags.
set -eu

prompt="${1:-}"
sid="${2:-}"

if [ -z "$prompt" ]; then
  echo "wake-claude: a handoff prompt is required" >&2
  exit 2
fi

if [ -n "$sid" ]; then
  exec claude -p "$prompt" --resume "$sid"
fi

exec claude -p "$prompt"
