/* ============================================================================
   TaskDashboard v1 prototype — interaction layer
   ----------------------------------------------------------------------------
   jQuery (slim build) only. Every binding uses `$(...).on(...)` with `data-*`
   hooks; no bare document.querySelector / addEventListener anywhere.
   No network, no storage, no tokens — this file is a pure static prototype.
   Interaction map: design-spec §6 (I1–I12).
   ========================================================================== */
(function ($) {
  "use strict";

  /* ------------------------------------------------------------------ data */

  var STATUSES = [
    "backlog",
    "todo",
    "in_progress",
    "in_review",
    "blocked",
    "done",
    "canceled",
  ];

  var STATUS_LABEL = {
    backlog: "Backlog",
    todo: "To Do",
    in_progress: "In Progress",
    in_review: "In Review",
    blocked: "Blocked",
    done: "Done",
    canceled: "Canceled",
  };

  var PRIORITY_LABEL = {
    urgent: "Urgent",
    high: "High",
    medium: "Medium",
    low: "Low",
    none: "None",
  };

  var PROJECT_PREFIX = {
    TaskDashboard: "TD",
    Orchestrator: "ORC",
    "Site Refresh": "SR",
  };

  /* Copy generated by the interaction layer. Keys mirror the data-i18n
     namespace used in index.html so the two stay translatable together. */
  var I18N = {
    "toast.moved": "Moved",
    "toast.commented": "Comment added",
    "toast.created": "Created",
    "toast.projectCreated": "Created project",
    "toast.projectSwitched": "Switched to project",
    "toast.copied": "Copied to clipboard",
    "toast.filtersCleared": "Filters cleared",
    "toast.themeDark": "Dark theme on",
    "toast.themeLight": "Light theme on",
    "toast.resume": "Resuming agent session",
    "toast.linked": "Opened linked task",
    "toast.activity": "Board revision",
    "toast.blocked": "This task is blocked",
    "theme.switchToDark": "Switch to dark theme",
    "theme.switchToLight": "Switch to light theme",
    "relations.none": "No relations",
    "attachments.none": "No attachments",
    "description.none": "No description yet.",
    "comment.author": "human",
    "comment.now": "just now",
    "placeholder.newProject": "New project",
    "list.emptyRow": "No task in this project",
  };

  var ME = "Mira Chen";

  var state = {
    project: "TaskDashboard",
    view: "board",
    moveIdentifier: null,
    searchTimer: null,
  };

  /* --------------------------------------------------------------- helpers */

  function text(key) {
    return I18N[key] || key;
  }

  /* Card scalars live in data-* attributes (design-spec §5.6). */
  function attr($el, name) {
    var value = $el.attr("data-" + name);
    return value === undefined || value === null ? "" : String(value);
  }

  function initials(name) {
    var parts = String(name).split(" ");
    var out = "";
    for (var i = 0; i < parts.length && out.length < 2; i++) {
      if (parts[i]) out += parts[i].charAt(0).toUpperCase();
    }
    return out || "?";
  }

  function numeric(id) {
    var n = String(id).replace(/[^0-9]/g, "");
    return n ? parseInt(n, 10) : 0;
  }

  /* ------------------------------------------------------- I12 · toast ---- */

  function toast(message, kind) {
    var $template = $("[data-toast-template]").html();
    if (!$template) return;
    var $item = $($.trim($template));
    $item.attr("data-toast-kind", kind || "info");
    $item.find("[data-toast-text]").text(message);
    $("[data-toast-region]").append($item);

    window.setTimeout(function () {
      $item.attr("data-state", "leaving");
      window.setTimeout(function () {
        $item.remove();
      }, 200);
    }, 2500);
  }

  /* Concurrent-write stand-in: every mutation advances the revision readout. */
  function bumpRevision() {
    var $value = $("[data-revision-value]");
    var next = parseInt($value.text(), 10) + 1;
    if (isNaN(next)) next = 1;
    $value.text(next);
  }

  /* ------------------------------------------------- board / column state */

  function refreshColumns() {
    $("[data-column]").each(function () {
      var $column = $(this);
      var visible = $column.find("[data-card]:not([hidden])").length;
      $column.find("[data-column-count]").text(visible);
      $column
        .find('[data-empty][data-empty-kind="column"]')
        .prop("hidden", visible !== 0);
    });
  }

  /* I1/I2 · single place where a card changes status. */
  function moveCard($card, status, announce) {
    if (!$card.length || STATUSES.indexOf(status) === -1) return;

    var identifier = attr($card, "identifier");
    var previous = attr($card, "status");
    if (previous === status) return;

    var $body = $(
      '[data-column][data-status="' + status + '"] [data-column-body]'
    );
    if (!$body.length) return;

    var $empty = $body.find('[data-empty][data-empty-kind="column"]');
    if ($empty.length) {
      $empty.before($card);
    } else {
      $body.append($card);
    }

    $card.attr("data-status", status);
    $card.attr("data-done", String(status === "done"));
    $card.attr("data-canceled", String(status === "canceled"));
    $card.find("[data-card-stripe]").attr("title", STATUS_LABEL[status]);

    refreshColumns();

    if (announce !== false) {
      toast(
        text("toast.moved") +
          " " +
          identifier +
          " → " +
          STATUS_LABEL[status],
        status === "blocked" ? "danger" : "success"
      );
      bumpRevision();
      if (state.view === "list") renderList();
    }
  }

  /* I6 / I8 · one filter pass drives cards, column counts and the count readout */
  function applyFilters() {
    var query = $.trim(String($("[data-search-input]").val() || "")).toLowerCase();
    var byAssignee = $("[data-filter-assignee]").val();
    var byPriority = $("[data-filter-priority]").val();
    var byLabel = $("[data-filter-label]").val();

    var total = 0;
    var shown = 0;

    $("[data-card]").each(function () {
      var $card = $(this);

      if (attr($card, "project") !== state.project) {
        $card.prop("hidden", true);
        return;
      }
      total++;

      var ok = true;

      if (query) {
        var haystack = [
          $card.find("[data-card-title]").text(),
          attr($card, "identifier"),
          attr($card, "labels"),
          attr($card, "assignee"),
          attr($card, "priority"),
        ]
          .join(" ")
          .toLowerCase();
        ok = haystack.indexOf(query) !== -1;
      }

      if (ok && byAssignee !== "all") {
        ok =
          byAssignee === "me"
            ? attr($card, "assignee") === ME
            : attr($card, "assignee-kind") === byAssignee;
      }

      if (ok && byPriority !== "all") {
        ok = attr($card, "priority") === byPriority;
      }

      if (ok && byLabel !== "all") {
        ok =
          ("," + attr($card, "labels") + ",").indexOf("," + byLabel + ",") !==
          -1;
      }

      $card.prop("hidden", !ok);
      if (ok) shown++;
    });

    refreshColumns();

    $("[data-filter-count]").text(
      shown === total
        ? total + (total === 1 ? " task" : " tasks")
        : "showing " + shown + " of " + total
    );

    $('[data-empty][data-empty-kind="no-results"]').prop(
      "hidden",
      !(total > 0 && shown === 0)
    );

    if (state.view === "list") renderList();
  }

  function resetFilters() {
    $("[data-search-input]").val("");
    $("[data-filter-assignee]").val("all");
    $("[data-filter-priority]").val("all");
    $("[data-filter-label]").val("all");
    applyFilters();
  }

  /* -------------------------------------------------------- I7 · views ---- */

  function setView(view) {
    state.view = view;

    $("[data-board]").prop("hidden", view !== "board");
    $("[data-list]").prop("hidden", view !== "list");

    $("[data-view-toggle] [data-view]").each(function () {
      var $button = $(this);
      $button.attr(
        "aria-pressed",
        String($button.attr("data-view") === view)
      );
    });

    $("[data-nav-item]").each(function () {
      var $item = $(this);
      var name = $item.attr("data-nav-item");
      if (name !== "board" && name !== "list") return;
      if (name === view) {
        $item.attr("aria-current", "page");
      } else {
        $item.removeAttr("aria-current");
      }
    });

    if (view === "list") renderList();
  }

  /* List rows are derived from the cards that survived the current filters. */
  function renderList() {
    var $host = $("[data-list-rows]");
    var markup = $.trim($("[data-list-row-template]").html() || "");
    if (!$host.length || !markup) return;

    $host.empty();

    var rows = 0;
    $("[data-card]:not([hidden])").each(function () {
      var $card = $(this);
      var $row = $(markup);
      var status = attr($card, "status");
      var priority = attr($card, "priority");

      $row.attr("data-identifier", attr($card, "identifier"));
      $row.find("[data-list-identifier]").text(attr($card, "identifier"));
      $row.find("[data-list-title]").text($card.find("[data-card-title]").text());
      $row
        .find("[data-list-status]")
        .attr("data-status", status)
        .find("[data-list-status-label]")
        .text(STATUS_LABEL[status]);
      $row.find("[data-list-assignee]").text(attr($card, "assignee"));
      $row
        .find("[data-list-priority]")
        .attr("data-priority", priority)
        .attr("aria-label", "Priority: " + (PRIORITY_LABEL[priority] || priority))
        .find("[data-list-priority-label]")
        .text(PRIORITY_LABEL[priority] || priority);
      $row.find("[data-list-revision]").text(attr($card, "version"));
      $host.append($row);
      rows++;
    });

    if (!rows) {
      $host.append(
        $('<div class="td-empty"></div>').append(
          $('<span class="td-empty-title"></span>').text(text("list.emptyRow"))
        )
      );
    }
  }

  /* ------------------------------------------------------- I3 · details --- */

  function openDetail($card) {
    if (!$card || !$card.length) return;

    var data = {
      identifier: attr($card, "identifier"),
      internalId: attr($card, "id"),
      status: attr($card, "status"),
      priority: attr($card, "priority"),
      project: attr($card, "project"),
      assignee: attr($card, "assignee"),
      kind: attr($card, "assignee-kind"),
      version: attr($card, "version"),
    };

    var $drawer = $("[data-detail-drawer]");

    /* head + property grid -------------------------------------------------- */
    $drawer.find("[data-detail-identifier]").text(data.identifier);
    $drawer
      .find("[data-detail-title]")
      .text($card.find("[data-card-title]").text() || data.identifier);

    $drawer
      .find("[data-detail-status-chip]")
      .attr("data-status", data.status)
      .find("[data-detail-status-chip-label]")
      .text(STATUS_LABEL[data.status]);

    $drawer
      .find("[data-detail-status]")
      .attr("data-status", data.status)
      .find("[data-detail-status-label]")
      .text(STATUS_LABEL[data.status]);

    var $priority = $drawer.find("[data-detail-priority]");
    $priority.attr("data-priority", data.priority);
    $priority.find("[data-detail-priority-label]").text(
      PRIORITY_LABEL[data.priority]
    );
    $priority
      .find(".td-pri")
      .attr("aria-label", "Priority: " + PRIORITY_LABEL[data.priority]);

    var $avatar = $drawer.find("[data-detail-assignee-avatar]");
    $avatar.text(initials(data.assignee)).attr("data-assignee-kind", data.kind);
    $avatar.attr("title", data.assignee);
    $drawer.find("[data-detail-assignee-label]").text(data.assignee);
    $drawer.find("[data-detail-assignee]").attr("data-assignee-kind", data.kind);

    $drawer.find("[data-detail-project-label]").text(data.project);
    $drawer.find("[data-detail-id]").text(data.internalId);
    $drawer.find("[data-detail-id-copy]").attr("data-copy-value", data.internalId);
    $drawer.find("[data-detail-version]").text(data.version);

    /* per-card body sections (inline <template data-detail-for="…">) -------- */
    var markup = $.trim(
      $('template[data-detail-for="' + data.identifier + '"]').html() || ""
    );
    var $source = $('<div data-detail-slot-source hidden></div>').append(
      markup ? $(markup) : ""
    );

    function fill(target, name, emptyKey) {
      var $target = $drawer.find(target);
      var $slot = $source.find('[data-slot="' + name + '"]');
      $target.empty();
      if ($slot.length && $slot.children().length) {
        $target.append($slot.children());
      } else if (emptyKey) {
        $target.append(
          $('<span class="text-xs text-td-ink-3"></span>').text(text(emptyKey))
        );
      }
    }

    fill("[data-detail-description]", "description", "description.none");
    fill("[data-detail-relations]", "relations", "relations.none");
    fill("[data-detail-attachments]", "attachments", "attachments.none");
    fill("[data-detail-comments]", "comments", null);
    fill("[data-detail-activity]", "activity", null);

    var $sessionSlot = $source.find('[data-slot="agent-session"]');
    var $sessionSection = $drawer.find("[data-detail-agent-session]");
    var $sessionBody = $drawer.find("[data-detail-agent-session-body]");
    $sessionBody.empty();
    if ($sessionSlot.length && $sessionSlot.children().length) {
      $sessionBody.append($sessionSlot.children());
      $sessionSection.prop("hidden", false);
    } else {
      $sessionSection.prop("hidden", true);
    }

    $source.remove();

    /* selection + open state ----------------------------------------------- */
    $("[data-card]").attr("aria-selected", "false");
    $card.attr("aria-selected", "true");
    $("[data-detail-overlay]").prop("hidden", false).width();
    $("[data-detail-overlay]").attr("data-state", "open");
    $drawer.attr("data-state", "open").attr("aria-hidden", "false");
    $drawer.find("[data-detail-close]").trigger("focus");
  }

  function closeDetail() {
    var $drawer = $("[data-detail-drawer]");
    if ($drawer.attr("data-state") !== "open") return;
    $drawer.attr("data-state", "closed").attr("aria-hidden", "true");
    $("[data-detail-overlay]").attr("data-state", "closed");
    window.setTimeout(function () {
      if ($("[data-detail-overlay]").attr("data-state") === "closed") {
        $("[data-detail-overlay]").prop("hidden", true);
      }
    }, 200);
    $("[data-card]").attr("aria-selected", "false");
  }

  /* ------------------------------------------------------- I2 · move menu - */

  function closeMoveMenu() {
    $("[data-move-menu]").prop("hidden", true).removeAttr("style");
    $("[data-card-menu]").attr("aria-expanded", "false");
  }

  function openMoveMenu($button) {
    var $menu = $("[data-move-menu]");
    var $card = $button.closest("[data-card]");
    state.moveIdentifier = attr($card, "identifier");

    $menu.prop("hidden", false);
    var offset = $button.offset();
    var width = $menu.outerWidth();
    var left = Math.max(
      8,
      Math.min(
        offset.left + $button.outerWidth() - width,
        $(window).width() - width - 8
      )
    );
    $menu
      .css({
        position: "fixed",
        top: offset.top + $button.outerHeight() + 4 + "px",
        left: left + "px",
        zIndex: 70,
      })
      .find("[data-move-to]")
      .each(function () {
        var current = $(this).attr("data-move-to") === attr($card, "status");
        $(this).attr("aria-current", String(current));
      });

    $button.attr("aria-expanded", "true");
  }

  /* --------------------------------------------------------- I9/I10 · modal */

  /* A native <dialog> can only be opened through showModal()/close(), which
     jQuery has no equivalent for — hence the direct element calls below. */
  function openModal(selector) {
    var el = $(selector)[0];
    if (el && typeof el.showModal === "function" && !el.open) el.showModal();
    else if (el) el.setAttribute("open", "open");
  }

  function closeModal(selector) {
    var el = $(selector)[0];
    if (el && typeof el.close === "function") el.close();
  }

  function nextIdentifier(project) {
    var prefix = PROJECT_PREFIX[project] || "TD";
    var highest = 0;
    $("[data-card]").each(function () {
      var id = attr($(this), "identifier");
      if (id.indexOf(prefix + "-") === 0) {
        highest = Math.max(highest, numeric(id));
      }
    });
    return prefix + "-" + (highest + 1);
  }

  function newInternalId() {
    var stamp = String(new Date().getTime()).slice(-8);
    return "td_01HQ9" + stamp;
  }

  var PRI_GLYPH =
    '<svg class="td-pri-glyph" viewBox="0 0 12 12" aria-hidden="true" focusable="false">' +
    '<rect x="2.5" y="2.5" width="7" height="7" rx="1"></rect>' +
    '<line x1="2" y1="6" x2="10" y2="6"></line></svg>';

  var ICON_RELATION =
    '<svg class="td-icon td-icon-sm" viewBox="0 0 24 24" aria-hidden="true" focusable="false">' +
    '<path d="M10 14a3.5 3.5 0 0 0 5 0l3-3a3.5 3.5 0 0 0-5-5l-1 1M14 10a3.5 3.5 0 0 0-5 0l-3 3a3.5 3.5 0 0 0 5 5l1-1"></path></svg>';
  var ICON_ATTACH =
    '<svg class="td-icon td-icon-sm" viewBox="0 0 24 24" aria-hidden="true" focusable="false">' +
    '<path d="M21 11 12.3 20a5 5 0 0 1-7-7l9.2-9.2a3.3 3.3 0 1 1 4.7 4.7l-9.2 9.2a1.7 1.7 0 1 1-2.3-2.4l8.5-8.5"></path></svg>';
  var ICON_COMMENT =
    '<svg class="td-icon td-icon-sm" viewBox="0 0 24 24" aria-hidden="true" focusable="false">' +
    '<path d="M20 12a7.5 7.5 0 0 1-7.5 7.5H8l-4 2.5V12A7.5 7.5 0 0 1 11.5 4.5h1A7.5 7.5 0 0 1 20 12Z"></path></svg>';
  var ICON_KEBAB =
    '<svg class="td-icon td-icon-sm" viewBox="0 0 24 24" aria-hidden="true" focusable="false">' +
    '<circle cx="12" cy="5" r="1.4" fill="currentColor" stroke="none"></circle>' +
    '<circle cx="12" cy="12" r="1.4" fill="currentColor" stroke="none"></circle>' +
    '<circle cx="12" cy="19" r="1.4" fill="currentColor" stroke="none"></circle></svg>';

  /* Builds the same hook-complete card markup as the static board. */
  function buildCard(task) {
    var $card = $('<article class="td-card" data-card draggable="true"></article>');
    $card.attr({
      "data-identifier": task.identifier,
      "data-id": task.internalId,
      "data-status": task.status,
      "data-priority": task.priority,
      "data-project": task.project,
      "data-assignee": task.assignee,
      "data-assignee-kind": task.kind,
      "data-labels": task.labels.join(","),
      "data-version": "v1",
      "data-comments": "0",
      "data-attachments": "0",
      "data-relations-parent": "0",
      "data-relations-blocks": "0",
      "data-relations-related": "0",
      "data-done": String(task.status === "done"),
      "data-canceled": String(task.status === "canceled"),
    });

    var $stripe = $(
      '<span class="td-card-stripe" data-card-stripe aria-hidden="true"></span>'
    ).attr("title", STATUS_LABEL[task.status]);
    $card.append($stripe);

    var $menu = $(
      '<button type="button" class="td-card-menu" data-card-menu aria-haspopup="menu" aria-expanded="false"></button>'
    )
      .attr("aria-label", "Move " + task.identifier + " to another column")
      .append(ICON_KEBAB);
    $card.append(
      $('<div class="td-card-top"></div>')
        .append(
          $('<span class="td-card-id" data-card-identifier></span>').text(
            task.identifier
          )
        )
        .append($menu)
    );

    $card.append(
      $('<button type="button" class="td-card-title" data-card-title></button>').text(
        task.title
      )
    );

    var $labels = $('<div class="td-card-labels" data-card-labels></div>');
    $.each(task.labels, function (index, label) {
      $labels.append(
        $('<span class="td-chip td-chip-label"></span>')
          .attr("data-label", label)
          .text(label)
      );
    });
    if (task.labels.length) $card.append($labels);

    var $priority = $('<span class="td-pri" data-card-priority role="img"></span>')
      .attr("aria-label", "Priority: " + PRIORITY_LABEL[task.priority])
      .attr("title", "Priority: " + PRIORITY_LABEL[task.priority])
      .append(PRI_GLYPH);

    var $avatar = $('<span class="td-avatar" data-card-assignee></span>')
      .attr("title", task.assignee)
      .text(initials(task.assignee));

    var $badge = $('<span class="td-agent-badge" data-card-agent-badge hidden></span>');
    if (task.kind === "agent") {
      $avatar.prop("hidden", true);
      $badge
        .prop("hidden", false)
        .attr("data-agent-platform", task.platform)
        .text(task.platform);
    }

    var $meta =
      '<span class="td-meta" data-card-relations hidden>' +
      '<span data-relation-parent hidden>' +
      ICON_RELATION +
      '<span class="td-mono">0</span></span>' +
      '<span data-relation-blocks hidden>' +
      ICON_RELATION +
      '<span class="td-mono">0</span></span>' +
      '<span data-relation-related hidden>' +
      ICON_RELATION +
      '<span class="td-mono">0</span></span></span>' +
      '<span class="td-meta" data-card-attachment-count hidden title="Attachments">' +
      ICON_ATTACH +
      '<span class="td-mono">0</span></span>' +
      '<span class="td-meta" data-card-comment-count hidden title="Comments">' +
      ICON_COMMENT +
      '<span class="td-mono">0</span></span>';

    $card.append(
      $('<div class="td-card-foot"></div>')
        .append($priority)
        .append($avatar)
        .append($badge)
        .append($('<div class="td-card-foot-right"></div>').append($meta))
    );

    return $card;
  }

  function insertCard($card, status) {
    var $body = $('[data-column][data-status="' + status + '"] [data-column-body]');
    if (!$body.length) return false;
    var $empty = $body.find('[data-empty][data-empty-kind="column"]');
    if ($empty.length) {
      $empty.before($card);
    } else {
      $body.append($card);
    }
    return true;
  }

  function setProject(project, announce) {
    state.project = project;
    $("[data-project-current]").text(project);

    $("[data-project-option]").each(function () {
      var $option = $(this);
      if ($option.attr("data-project-option") === project) {
        $option.attr("aria-current", "true");
      } else {
        $option.removeAttr("aria-current");
      }
    });

    $("[data-project-list] [data-project]").each(function () {
      var $item = $(this);
      if ($item.attr("data-project") === project) {
        $item.attr("aria-current", "page");
      } else {
        $item.removeAttr("aria-current");
      }
    });

    applyFilters();

    if (announce) {
      toast(text("toast.projectSwitched") + " " + project, "info");
    }
  }

  /* ---------------------------------------------------- clipboard helper -- */

  /* Clipboard writes need the Selection API and document.execCommand, which
     have no jQuery equivalent — used only here, with a throwaway helper node. */
  function copyText(value) {
    if (!value) return;
    var helper = document.createElement("textarea");
    helper.value = value;
    helper.setAttribute("readonly", "readonly");
    document.body.appendChild(helper);
    helper.select();
    var ok = false;
    try {
      ok = document.execCommand("copy");
    } catch (error) {
      ok = false;
    }
    document.body.removeChild(helper);
    toast(ok ? text("toast.copied") + ": " + value : value, ok ? "success" : "info");
  }

  /* =========================================================== bindings === */

  $(function () {
    /* I7 · view toggle ----------------------------------------------------- */
    $("[data-view-toggle]").on("click", "[data-view]", function () {
      setView($(this).attr("data-view"));
    });

    $("[data-nav]").on("click", "[data-nav-item]", function () {
      var name = $(this).attr("data-nav-item");
      if (name === "board" || name === "list") {
        setView(name);
        return;
      }
      var $count = $("[data-filter-count]");
      toast(
        text("toast.activity") +
          " " +
          $("[data-revision-value]").text() +
          " · " +
          $count.text(),
        "info"
      );
    });

    /* B04 · filters -------------------------------------------------------- */
    var debouncedFilter = function () {
      window.clearTimeout(state.searchTimer);
      state.searchTimer = window.setTimeout(applyFilters, 150);
    };

    $("[data-search]").on("input", "[data-search-input]", debouncedFilter);
    $("[data-filters]").on(
      "change",
      "[data-filter-assignee], [data-filter-priority], [data-filter-label]",
      applyFilters
    );
    $(document).on("click", "[data-filter-clear]", function () {
      resetFilters();
      toast(text("toast.filtersCleared"), "info");
    });
    $("[data-filter-toggle]").on("click", function () {
      var $button = $(this);
      var open = $button.attr("aria-pressed") !== "true";
      $button.attr("aria-pressed", String(open));
      $("[data-filters]").prop("hidden", !open);
    });

    /* I8 · project switching ---------------------------------------------- */
    $("[data-project-switcher]").on("click", "[data-project-option]", function () {
      $("[data-project-switcher]").removeAttr("open");
      setProject($(this).attr("data-project-option"), true);
    });
    $("[data-project-list]").on("click", "[data-project]", function () {
      setProject($(this).attr("data-project"), true);
    });

    /* I3 · open detail (card body, or the title button inside it) --------- */
    $("[data-board], [data-list]").on("click", "[data-card]", function (event) {
      if ($(event.target).closest("[data-card-menu], [data-move-menu]").length) {
        return;
      }
      openDetail($(this));
    });

    /* I4 · close detail ---------------------------------------------------- */
    $("[data-detail-close]").on("click", closeDetail);
    $("[data-detail-overlay]").on("click", closeDetail);

    $(document).on("keydown", function (event) {
      if (event.key === "Escape" || event.key === "Esc") {
        closeMoveMenu();
        closeDetail();
      }
    });

    /* I2 · card menu → move ------------------------------------------------- */
    $("[data-board]").on("click", "[data-card-menu]", function (event) {
      event.stopPropagation();
      closeMoveMenu();
      openMoveMenu($(this));
    });

    $("[data-move-menu]").on("click", "[data-move-to]", function () {
      var status = $(this).attr("data-move-to");
      var $card = $(
        '[data-card][data-identifier="' + state.moveIdentifier + '"]'
      );
      closeMoveMenu();
      moveCard($card, status, true);
    });

    $(document).on("click", function (event) {
      if (!$(event.target).closest("[data-move-menu], [data-card-menu]").length) {
        closeMoveMenu();
      }
    });

    /* I1 · drag and drop --------------------------------------------------- */
    $("[data-board]").on("dragstart", "[data-card]", function (event) {
      var original = event.originalEvent;
      var $card = $(this);
      state.moveIdentifier = attr($card, "identifier");
      $card.attr("data-dragging", "true");
      if (original && original.dataTransfer) {
        original.dataTransfer.effectAllowed = "move";
        original.dataTransfer.setData("text/plain", state.moveIdentifier);
      }
    });

    $("[data-board]").on("dragend", "[data-card]", function () {
      $(this).removeAttr("data-dragging");
      $("[data-column]").removeAttr("data-drag-over");
      $("[data-drop-placeholder]").remove();
    });

    $("[data-board]").on("dragover", "[data-column-body]", function (event) {
      event.preventDefault();
      var original = event.originalEvent;
      var $body = $(this);
      if (original && original.dataTransfer) {
        original.dataTransfer.dropEffect = "move";
      }
      $("[data-column]").not($body.closest("[data-column]")).removeAttr("data-drag-over");
      $body.closest("[data-column]").attr("data-drag-over", "true");
      if (!$body.find("[data-drop-placeholder]").length) {
        $body.append('<div class="td-drop-placeholder" data-drop-placeholder></div>');
      }
    });

    $("[data-board]").on("dragleave", "[data-column-body]", function (event) {
      var original = event.originalEvent;
      if (original && original.relatedTarget && $.contains(this, original.relatedTarget)) {
        return;
      }
      $(this).closest("[data-column]").removeAttr("data-drag-over");
      $(this).find("[data-drop-placeholder]").remove();
    });

    $("[data-board]").on("drop", "[data-column-body]", function (event) {
      event.preventDefault();
      var $body = $(this);
      var original = event.originalEvent;
      var identifier =
        state.moveIdentifier ||
        (original && original.dataTransfer
          ? original.dataTransfer.getData("text/plain")
          : "");

      $("[data-column]").removeAttr("data-drag-over");
      $("[data-drop-placeholder]").remove();

      moveCard(
        $('[data-card][data-identifier="' + identifier + '"]'),
        $body.closest("[data-column]").attr("data-status"),
        true
      );
    });

    /* I5 · comment --------------------------------------------------------- */
    $("[data-comment-form]").on("submit", function (event) {
      event.preventDefault();
      var $form = $(this);
      var $input = $form.find("[data-comment-input]");
      var body = $.trim(String($input.val() || ""));
      if (!body) {
        $input.trigger("focus");
        return;
      }

      var $comment = $('<article class="td-comment"></article>');
      $comment.append(
        $('<span class="td-avatar"></span>').text(initials(ME))
      );
      $comment.append(
        $("<div></div>")
          .append(
            $('<div class="td-comment-meta"></div>')
              .append(
                $('<span class="font-medium text-td-ink"></span>').text(ME)
              )
              .append(
                $("<span></span>")
                  .attr("data-i18n", "comment.human")
                  .text(text("comment.author"))
              )
              .append(
                $('<span class="td-mono"></span>').text(text("comment.now"))
              )
          )
          .append($('<div class="td-comment-body"></div>').text(body))
      );

      $("[data-detail-comments]").prepend($comment);
      $input.val("");

      var identifier = $("[data-detail-identifier]").text();
      var $card = $('[data-card][data-identifier="' + identifier + '"]');
      if ($card.length) {
        var count = parseInt(attr($card, "comments"), 10) + 1;
        if (isNaN(count)) count = 1;
        $card.attr("data-comments", count);
        $card
          .find("[data-card-comment-count]")
          .prop("hidden", false)
          .find(".td-mono")
          .text(count);
      }

      toast(text("toast.commented"), "success");
      bumpRevision();
    });

    /* I9 · create task ----------------------------------------------------- */
    $("[data-new-task]").on("click", function () {
      $("[data-create-task-project]").val(state.project);
      openModal("[data-create-task]");
    });

    $("[data-board]").on("click", "[data-column-add]", function () {
      var status = $(this).closest("[data-column]").attr("data-status");
      $("[data-create-task-status]").val(status);
      $("[data-create-task-project]").val(state.project);
      openModal("[data-create-task]");
    });

    $("[data-create-task-form]").on("submit", function (event) {
      event.preventDefault();
      var $form = $(this);
      var title = $.trim(String($form.find("[data-create-task-title]").val() || ""));
      if (!title) {
        $form.find("[data-create-task-title]").trigger("focus");
        return;
      }

      var $assignee = $form.find("[data-create-task-assignee] option:selected");
      var status = $form.find("[data-create-task-status]").val();
      var project = $form.find("[data-create-task-project]").val();

      var task = {
        identifier: nextIdentifier(project),
        internalId: newInternalId(),
        title: title,
        status: status,
        priority: $form.find("[data-create-task-priority]").val(),
        assignee: $assignee.val(),
        kind: $assignee.attr("data-assignee-kind") || "human",
        platform: String($assignee.val() || "").toLowerCase(),
        project: project,
        labels: [],
      };

      var $card = buildCard(task);
      var placed = insertCard($card, status);

      closeModal("[data-create-task]");
      /* jQuery has no form-reset equivalent, so the native method is used. */
      $form[0].reset();
      $("[data-create-task-project]").val(state.project);
      $("[data-create-task-status]").val("backlog");
      $("[data-create-task-priority]").val("none");

      if (!placed) return;
      applyFilters();
      toast(text("toast.created") + " " + task.identifier, "success");
      bumpRevision();
    });

    /* I10 · create project ------------------------------------------------- */
    $("[data-project-switcher]").on("click", "[data-project-new]", function () {
      $("[data-project-switcher]").removeAttr("open");
      openModal("[data-create-project]");
    });

    $("[data-create-project-form]").on("submit", function (event) {
      event.preventDefault();
      var $form = $(this);
      var name = $.trim(String($form.find("[data-create-project-name]").val() || ""));
      var prefix = $.trim(
        String($form.find("[data-create-project-prefix]").val() || "")
      ).toUpperCase();
      if (!name || !prefix) {
        $form.find("[data-create-project-name]").trigger("focus");
        return;
      }

      var $entry = $(
        '<button type="button" class="td-side-item" data-project></button>'
      )
        .attr("data-project", name)
        .append($('<span class="td-side-name td-mono"></span>').text(name))
        .append($('<span class="td-count" data-project-count></span>').text("0"));
      $("[data-project-list]").append($entry);

      var $option = $(
        '<li><button type="button" data-project-option></button></li>'
      );
      $option
        .find("button")
        .attr("data-project-option", name)
        .append($('<span class="td-mono"></span>').text(name));
      $("[data-project-switcher] .menu [data-project-new]")
        .closest("li")
        .before($option);

      $("[data-create-task-project]").append(
        $("<option></option>").attr("value", name).text(name)
      );
      PROJECT_PREFIX[name] = prefix;

      closeModal("[data-create-project]");
      /* jQuery has no form-reset equivalent, so the native method is used. */
      $form[0].reset();
      setProject(name, false);
      toast(text("toast.projectCreated") + " " + name, "success");
    });

    /* modals — the Cancel buttons close their own dialog ------------------- */
    $("[data-create-task]").on("click", "[data-modal-close]", function () {
      closeModal("[data-create-task]");
    });
    $("[data-create-project]").on("click", "[data-modal-close]", function () {
      closeModal("[data-create-project]");
    });

    /* I11 · theme ---------------------------------------------------------- */
    $("[data-theme-toggle]").on("click", function () {
      var $button = $(this);
      var dark = $("html").attr("data-theme") !== "dark";
      $("html").attr("data-theme", dark ? "dark" : "taskdash");
      $button.attr("aria-pressed", String(dark));
      $button.attr(
        "aria-label",
        dark ? text("theme.switchToLight") : text("theme.switchToDark")
      );
      $button.find('[data-theme-icon="light"]').prop("hidden", dark);
      $button.find('[data-theme-icon="dark"]').prop("hidden", !dark);
      toast(dark ? text("toast.themeDark") : text("toast.themeLight"), "info");
    });

    /* detail extras -------------------------------------------------------- */
    $("[data-detail-id-copy]").on("click", function () {
      copyText($(this).attr("data-copy-value"));
    });

    $("[data-detail-drawer]").on("click", "[data-agent-session-id]", function () {
      copyText($.trim($(this).text()));
    });

    $("[data-detail-drawer]").on("click", "[data-agent-resume]", function () {
      toast(text("toast.resume"), "info");
    });

    $("[data-detail-drawer]").on("click", "[data-relation-link]", function () {
      var identifier = $.trim($(this).text());
      var $card = $('[data-card][data-identifier="' + identifier + '"]');
      if ($card.length) {
        openDetail($card);
        toast(text("toast.linked") + " " + identifier, "info");
      } else {
        toast(identifier, "info");
      }
    });

    /* list rows open the same drawer -------------------------------------- */
    $("[data-list]").on("click", "[data-list-row]", function () {
      var $card = $(
        '[data-card][data-identifier="' + $(this).attr("data-identifier") + '"]'
      );
      if ($card.length) openDetail($card);
    });

    /* ---------------------------------------------------------- first pass */
    $("[data-detail-overlay]").prop("hidden", true);
    $("[data-detail-drawer]").attr("aria-hidden", "true");
    applyFilters();
  });
})(jQuery);
